name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests
      run: |
      xcodebuild -list
      xcodebuild -workspace BSGToolbarView.xcworkspace -scheme BSGToolbarView test | xcbeautify
