name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests
      run: |
        xcodebuild -list
        xcodebuild -workspace BSGToolbarView.xcworkspace -scheme BSGToolbarView test | xcbeautify
