name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Tests
    runs-on: macos-15

    steps:
    
    # Check out the repository.
    - name: Checkout
      uses: actions/checkout@v4
    
    # Install gems needed for Fastlane.
    - name: Install Gems
      run: |
        gem install bundler
        bundle install
        
    # Run unit tests with Fastlane.
    - name: Fastlane Scan
      run: bundle exec fastlane test
