name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests
      run: |
        xcodebuild -scheme BSGToolbarView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' test | xcbeautify >> test-result.txt
        grep -q 'Tests Failed' test-result.txt && exit 1
